// poyoweb-client/src/routes/auth/+page.svelte
<script lang="ts">
	import type { PageData, ActionData } from './$types';
	import { enhance } from '$app/forms';

	// Define the form properties
	interface FormData {
		loginSuccess?: boolean;
		incorrect?: boolean;
		registerSuccess?: boolean;
		registerError?: string;
	}

	let { form }: { data: PageData; form: FormData } = $props();
</script>

<h1>PAPERS, PLEASE!</h1>
<p>Nah you're not getting thru TSA, katanas aren't allowed :P</p>

<form method="POST" action="?/login" use:enhance>
	{#if form?.incorrect}
		<p class="error">Wrong email or password!</p>
	{/if}
	<label>
		Email:
		<input type="email" name="email" required />
	</label>
	<label>
		Password:
		<input type="password" name="password" required />
	</label>

	<button type="submit">Login</button>
</form>

<form method="POST" action="?/register" use:enhance>
	<label>
		Username:
		<input type="text" name="username" required />
	</label>
	<label>
		Email:
		<input type="email" name="email" required />
	</label>
	<label>
		Password:
		<input type="password" name="password" required />
	</label>

	<button type="submit">Register</button>
	{#if form?.registerSuccess}
		<p class="success">Registration successful!</p>
	{/if}

	{#if form?.registerError}
		<p class="error">Registration error: {form.registerError}</p>
	{/if}
</form>

<style>
	.error {
		color: red;
	}
</style>

// src/components/auth.tsx
import { Html, html } from '@elysiajs/html';

const authHtml = ({ user }: { user?: { username: string } }) => ( 
    <>
        <h1>Authenticate</h1>
        <form method="post" action="/auth/login">
            <h2>Login</h2>
            <label for="username">Username</label>
            <input type="text" id="username" name="username" /><br/>
            <label for="password">Password</label>
            <input type="password" id="password" name="password" /><br/>
            <input type="submit" />
        </form>
        <form method="post" action="/auth/register">
            <h2>Register</h2>
            <label for="username">Username</label>
            <input type="text" id="username" name="username" /><br/>
            <label for="password">Password</label>
            <input type="password" id="password" name="password" /><br/>
            <label for="email">Email</label>
            <input type="email" id="email" name="email" /><br/>
            <input type="submit" />
        </form>
    </>
);

export default authHtml;
